wipe=true
output="internal/sqlboiler"
pkgname="sqlboiler"
add-global-variant=true
add-enum-types=true
no-hooks=false
no-tests=true
add-soft-deletes=true
auto-columns=["created_at", "updated_at"]

[psql]
dbname = "smap"
host = "172.16.19.10"
port = 5432
user = "knowledge_prod"
pass = "knowledge_prod_pwd"
sslmode = "disable"
schema = "schema_knowledge"
blacklist = [
    "schema_migrations",
    "repmgr_*",
    "pg_stat_*",
    "information_schema.*"
]
